export const config = {
 primaryColor : "#0d6efd",
 secondaryColor: "#7a7a7a",
 error:"#dc3545",
 warning:"#ffc107",
 success:"#198754",
 info:"#0dcaf0",
 hover: "#008FCB",
 textColor:"black",
 lightColor: "#F9F9F9",
 borderColor: " #DDDDDD",
 borderRadius: "4px",
 borderWidth: "1px",
 border:"1px solid",
 buttonColorPrimary:"#fff",
 buttonColorSecondary:"#fff",
 defaultSpacing:"8px",
 smSpacing:"5px",
 lgSpacing:"16px",
 xlSpacing:"24px",
 defaultFontsize:"16px",
 smFontsize:"13px",
 lgFontsize:"18px",
 xlFontsize:"22px",
 transaprantBackground:"transparent"
}