export const CONSTANTS = {
	VARIANT: {
		solid: "solid",
		light: "light",
		dark: "dark",
		hallow: "hallow",
		ghost: "ghost",
	},
	ACCENT: {
		primary: "primary",
		secondary: "secondary",
		error: "error",
		info: "info",
		success: "success",
		warning: "warning",
		disabled: "disabled",
		image: "image",
	},
	SIZE: {
		default: "default",
		small: "small",
		large: "large",
		xtraLarge: "xtraLarge",
	},
	TYPE: {
		number: "number",
		roman: "roman",
		bullet: "bullet",
		image: "image",
	},
	primaryColor: "#1AB5EB",
	primaryHover: "1AB5EB0D",
	secondaryColor: "#7a7a7a",
	secondaryHover: "7a7a7a0D",
	error: "#eb3f27",
	errorHover:"#eb3f270D",
	warning: "#ffc107",
	warningHover: "ffc1070D",
	success: "#4ebd1e",
	successHover:"#4ebd1e0D",
	info: "#008FCB",
	infoHover:"#008FCB0D",
	hover: "#008FCB",
	textColor: "black",
	lightColor: "#F9F9F9",
	borderColor: " #DDDDDD",
	borderRadius: "4px",
	borderWidth: "1px",
	border: "1px solid",
	buttonColorPrimary: "#fff",
	buttonColorSecondary: "#fff",
	defaultSpacing: "8px",
	smSpacing: "5px",
	lgSpacing: "16px",
	xlSpacing: "24px",
	defaultFontsize: "14px",
	smFontsize: "13px",
	lgFontsize: "15px",
	xlFontsize: "16px",
	transaprantBackground: "transparent",
};
